[package]
name = "masquerade"
version = "0.1.0"
edition = "2021"

[dependencies]
openssl = { version = "0.10.68", features = ["vendored"] }
rand = "0.8.5"
stun = { path = "../stun" }
sctp = { path = "../sctp" }
